<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>New Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>panduputra.ilham@gmail.com;</mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>715e098c-6bee-4ea5-bc1c-73803ba7d07e</testSuiteGuid>
   <testCaseLink>
      <guid>26769407-9840-4f37-aed9-483c91fdea2f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>f765ce06-a909-44c8-8f8f-43d479cfbb4a</id>
         <masked>false</masked>
         <name>variable</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/test</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8d75252f-26dd-4fc0-81e3-43006c2ebae2</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-5</value>
         </iterationEntity>
         <testDataId>Data Files/New Test Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>8d75252f-26dd-4fc0-81e3-43006c2ebae2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Penghasilan_total</value>
         <variableId>f765ce06-a909-44c8-8f8f-43d479cfbb4a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d9589d5d-6d1c-49f3-ac9b-6e8e97b1845d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/test1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>a5925e79-54ae-4c49-a166-c1137856be22</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Satu</testCaseId>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>79a4a32d-1397-49e1-8b5d-48f42119c79d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/New Test Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>79a4a32d-1397-49e1-8b5d-48f42119c79d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Penghasilan_total</value>
         <variableId>931b8f0c-e2e1-4e36-aa50-cef44d2cd20e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>79a4a32d-1397-49e1-8b5d-48f42119c79d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Pengeluaran</value>
         <variableId>f45d0728-1a5c-42dc-b155-798bba09facd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>79a4a32d-1397-49e1-8b5d-48f42119c79d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Jangka_Waktu</value>
         <variableId>cb03f7a0-f097-4dc1-9cef-420c8c212b2d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cd0a2ff4-be49-437d-bcc7-4573b09abd27</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dua</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d93c1644-d23a-4e14-8076-124245f1b8b6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/New Test Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d93c1644-d23a-4e14-8076-124245f1b8b6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Jangka_Waktu</value>
         <variableId>65a81fde-751d-4dbb-8b60-66c18e75c3b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d93c1644-d23a-4e14-8076-124245f1b8b6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Text</value>
         <variableId>f36ec251-8242-43b0-8439-f548afd80cb7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
