<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>test</name>
   <tag></tag>
   <elementGuidId>2a2c4aa5-6112-499a-addc-8aef809ef018</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>${value}</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>${value}</value>
      <webElementGuid>854b398c-30ed-4aaf-b7fc-c3080a1626a1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
